espressif/esp32-camera

driver/camera.c
driver/sccb.c

Fix for failed writes with OV2640:
#48 
```
I (11740) sccb: pin_sda 26 pin_scl 27
I (11750) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
E (11770) sccb: SCCB_Write Failed addr:0x3c, reg:0xff, data:0x01, ret:-1
E (11770) sccb: SCCB_Write Failed addr:0x3c, reg:0x12, data:0x80, ret:-1
```
also includes fix in if for disabling OV3360_SUPPORT and leaving only OV2640 which led to reset not being called

With SCCB_HARDWARE_I2C slave_addr was not used

---

CMakeLists.txt
driver/camera.c
driver/include/esp_camera.h

Add two new functions to esp_camera.h to assist in persistent camera settings in nvs. It would be useful to have changes to camera settings persist across reboots:
```
esp_err_t esp_camera_save_to_nvs(const char *key);
esp_err_t esp_camera_load_from_nvs(const char *key);
```
key is a unique name for the camera settings. It is possible to save different camera setting "profiles" by using different key names (which might be handy for say a day/night mode).
Both functions load/save a `camera_settings_t` structure to the nvs data partition as a blob. 
When loading the structure from the nvs, each individual setting has to be written using the sensor_t->set_xxx(s,value) methods or the setting won't be sent to the camera sensor.
I did consider writing each field to the nvs data store …

Feature: persistent storage of sensor settings in nvs

---

driver/xclk.c

in commit 2e8c85d8fff823232af46cc0f353ac170d0971e9 of esp-idf the ledc.c driver was changed and it no longer assumes APB clock use and it needs to be set explicitly

fixed clock config to explicitly use APB

---

driver/camera.c

raised kernel panic on gpio_isr_handler_add() because isr handler failed to register.

missing retvalue check

---

README.md

The boundary delimiter (`_STREAM_BOUNDARY`) needs to be send before the
body part (`_STREAM_PART`) too follow RFC2046. This caused `ffplay`/`ffmpeg`
to fail to open the MJPEG stream.
See also PR [espressif/arduino-esp32/pull/3720](https://github.com/espressif/arduino-esp32/pull/3720).

Move _STREAM_BOUNDARY before _STREAM_PART

---

driver/camera.c

If no interrupt was found, this call fails silently and the driver will eventually time out when trying to fetch a frame buffer.

Added missing retvalue check

---

conversions/to_bmp.c

esp_spiram.h before 4.0
esp32/spiram.h on 4.0

don't need that header, be careful the name is different in idf 4+ and 4-

---

README.md
examples/take_picture.c
library.json

This PR adds `library.json` to make this compatible with PlatformIO library ([docs on how to create a library](https://docs.platformio.org/en/latest/librarymanager/creating.html)).
It also adds an example to be shown on the library page and updates README to include the setup with PlatformIO.
- Using the library [`esp32-camera`](https://platformio.org/lib/show/10785/esp32-camera) to build for AI-Thinker board.

Port it as a library on PlatformIO

---

driver/camera.c

This is needed when reusing the i2c/sccb bus for multiple devices. Similar functionality accidentally made it into https://github.com/espressif/esp32-camera/pull/145 before being reverted.
cc: @apiesse

Allow skipping SCCB init using pin_sscb_sda = -1

---

driver/camera.c

Our hardware uses an external 10MHz oscillator in order to save a pin. This PR adds the ability to pass '-1' as a `pin_xclk`, causing the xclk functionality to be disabled.

Add support for external xclk

---

driver/sccb.c

In some cases, initialization fails because some flags are not set to zero

Bugfix: initialize i2c_config_t struct to zero

---

driver/camera.c

The uncontrolled output "bh: 0x0..." will be changed to the controllable output by using ESP_LOGD
esp_printf("bh: 0x -> ESP_LOGD(
This change also speed-up's the camera throughput a little (in case the log level is set to info or below)

Bugfix: disable uncontrollable output "bh: 0x...." in log

---

driver/camera.c

The error occurs during the camera initialization. The modification in the pull request solved the error, however, I am not sure the if the modification introduces other defects.

Fix "gpio_install_isr_service failed (105)" error.

---

target/esp32s2/private_include/tjpgd.h

- modify tjpgd output pixel format to RGB888

bugfix: fix tjpgd configuration for esp32s2

---

library.json

Project using this library wouldn't compile with this error:
.pio/libdeps/esp32cam/esp32-camera/driver/cam_hal.c:18:10: fatal error: ll_cam.h: No such file or directory
Adding this line seems to fix it.

Added missing library.json build flag

---

sensors/nt99141.c

This PR fixes some warnings about the `nt99141` sensor's driver implementation so we can build it with `-Werror`:
* actually return the `ret` variable in `set_framesize`
* remove unused variables in `set_brightness` and `set_contrast`
* remove unused function `calc_sysclk`

Fix nt99141 sensor

---

.github/workflows/build.yml
target/private_include/ll_cam.h

Fixes: https://github.com/espressif/esp32-camera/issues/332

Fix "periph_module_enable" not found in ESP-IDF v5

---

sensors/ov7670.c
sensors/ov7725.c

When I use OV7725 and OV7670, I can't get the image. This pr modifies the VSYNC register of OV7725 7670, and the image can be obtained normally, and the white balance is adjusted to make the obtained image normal.

bugfix:ov7725 vsync get frame failed

---

sensors/gc0308.c
sensors/gc2145.c

Depending on selected configuration, these may end up being unused and will cause warnings to be emitted on each recompile.

Silence unused variable warnings

---

driver/cam_hal.c
target/esp32/ll_cam.c
target/esp32s2/ll_cam.c
target/esp32s3/ll_cam.c

- When nvs_ set_ blob () and camera are used at the same time, it will trigger the device to restart (sometimes with log just like "Cache disabled but cached memory region accessed"）.      
- This PR provides a solution to the above problems.

fix: fix cache error when both nvs and camera used

---

CMakeLists.txt
conversions/esp_jpg_decode.c
conversions/jpge.cpp
conversions/to_bmp.c
conversions/to_jpg.cpp

Closes https://github.com/espressif/esp32-camera/issues/387

Compile conversions sources for all platforms (Also fixed SPIRAM checks for allocations)

---

sensors/gc0308.c
sensors/private_include/gc0308_settings.h

If REGLIST_TAIL is defined as 0x00, the register with address 0x00 will not be written correctly.

fix: fix gc0308 REGLIST_TAIL define error

---

sensors/private_include/ov5640_settings.h

The default register configuration of OV5640 sensor causes occasional configuration failures.  
This MR is used to provide a way to solve the problem.

fix: fix ov5640 sys reset to MCU mode reset

---

driver/cam_hal.c

The 128 bit aligned buffer have good performance for [esp_jpeg](https://github.com/espressif/esp-adf-libs/blob/master/esp_codec/include/codec/esp_jpeg_enc.h) encoding.  The aligned data to improve the memory load time, combined with esp32-S3 128bit SIMD instructions optimization, we got about 10 fps on OV3660 camera with YUV422 and  VGA.

Change the fb buffer as 16 bytes aligned

---

conversions/to_bmp.c

Reduces memory use for grayscale output.

Added support for 8-bit grayscale output to fmt2bmp() for frame2bmp()

---

target/esp32s3/ll_cam.c

@igrr This branch fixes compilation errors when XCLK is set to -1 and updates code formatting issues

fix bug when config->pin_xclk = -1 target esp32s3

---

target/xclk.c

`camera_disable_out_clock` is called (as `CAMERA_DISABLE_OUT_CLOCK()`) in `esp_camera_deinit()`
`camera_disable_out_clock()` stops the clock for LEDC channel `g_ledc_channel`. But if the camera was never enabled, it will stop channel `0`, which might be in use by other unrelated things.
This fix detects when there is no clock to stop.
See https://github.com/adafruit/esp32-camera/pull/1 for background.

don't reset LEDC channel if it wasn't used by camera

---

driver/cam_hal.c

We get a crash caused by a failing assert when we use the following config.  In particular we see the crash when using Grayscale and 96x96 resolution.   The platform is ESP32-S3 using PSRAM.  We traced it to cam_hal.c attempting to create a queue of size 0.  This PR has a change where we make sure the queue size is at least 1.   This fixes our case, but maybe there's a more elegant or robust way of fixing it.
```
config.ledc_channel  = LEDC_CHANNEL_0;
config.ledc_timer    = LEDC_TIMER_0;
config.pin_d0        = CAMERA_PIN_D0;
config.pin_d1        = CAMERA_PIN_D1;
config.pin_d2        = CAMERA_PIN_D2;
config.pin_d3        = CAMERA_PIN_D3;
config.pin_d4        = CAMERA_PIN_D4;
config.pin_d5        = CAMERA_PIN_D5;
config.pin_d6        = CAMERA_PIN_D6;
config.pin_d7        = CAMERA_PIN_D7; …
```

Fix: Make sure there is a queue size of at least 1.

---

target/esp32/ll_cam.c
target/esp32s2/ll_cam.c

Since `gpio_install_isr_service()` is called when initializing the camera, but on de-initiazlization the ISR service is not uninstalled. This causes an error `gpio_install_isr_service(410): GPIO isr service already installed` when the camera is re-initialized.

Uninstalls ISR service on cam deinit

---

target/esp32/ll_cam.c
target/xclk.c

With IDF 5.2 master it works with esp32-s3 but fails with esp32 standard, and has two problems:
First is that when compiling it does not find the function: ets_delay_us'. implicit declaration of function 'ets_delay_us';
Second that it fails to initialize xlock.
camera_xclk: ledc_timer_config failed, rc=103
The solution is to add #define ets_delay_us esp_rom_delay_us when the idf version is greater than 5 and initialize the variable timer_conf.deconfigure = false;

Fails with ESP32 (Standard) and not run with ESP-IDF v5.2

---

driver/cam_hal.c
target/esp32s3/ll_cam.c
target/private_include/ll_cam.h

Closes https://github.com/espressif/esp32-camera/issues/620

Create workaround for DMA failing on ESP32-S3 when WiFi is started

---

Kconfig
driver/cam_hal.c

This Pull Request provides an option in menuconfig to customize the buffer size for JPEG mode, addressing [Issue #663](https://github.com/espressif/esp32-camera/issues/663).
* Added a configurable option in Kconfig to choose between the default automatic calculation (width * height / 5) and specifying a custom buffer size.
* The default setting maintains the existing behavior, so it should not affect current code. However, please review carefully as I am not very experienced with this library.

Add option to customize JPEG mode frame size in menuconfig

---

CMakeLists.txt
driver/sccb-ng.c
driver/sccb.c

This PR removes the legacy I2C driver from the SCCB and implements the newer version (see issues #649 )
All interfaces outside the SCCB are entirely unchanged and identical!
I've tested the project with an OV2640 on an ESP32-Cam board - it functions identically.
To keep these identical I had to translate the unique i2c slave address to their distinctive `i2c_device_handle_t`.
This requires saving both of these in an array of a locally defined struct.
I'm not sure if this is an ideal solution moving forward but as it doesn't break anything outside of the SCCB I think this is reasonable (This whole translation thing is further explained in a comment from line 51 onwards)
Currently this requires the esp-idf head version (not the latest release), as the code makes heavy use of the …

Implement new idf-v5 I2C driver

---

.github/workflows/build.yml
target/esp32s3/ll_cam.c

IDF v5.3 added and EOL IDF v4.4 removed

Fix deprecation in IDF 5.4+ and update IDF build versions

---

driver/esp_camera.c

GCC 14 adds "calloc-transposed-args" warning which is an error at the default IDF build settings.
https://github.com/espressif/esp32-camera/actions/runs/10878656538/job/30181924334

fix: correct calloc call arguments order

---

CMakeLists.txt
Kconfig
driver/esp_camera.c
driver/include/sensor.h
driver/sensor.c
examples/camera_example/main/CMakeLists.txt
examples/camera_example/main/take_picture.c
sensors/mega_ccm.c
sensors/private_include/mega_ccm.h
sensors/private_include/mega_ccm_regs.h
sensors/private_include/mega_ccm_settings.h

Add mega ccm driver support

---

target/xclk.c

LEDC driver was extended in https://github.com/espressif/esp-idf/commit/4a90deb2278322e6c605484770caafebfbbc615f with new config structure members. We must zero init the config struct to get default behavior.
* Needed because of https://github.com/espressif/esp-idf/commit/4a90deb2278322e6c605484770caafebfbbc615f
Run esp32-camera example on S2 board.
---

fix(xclk): Zero init ledc_channel_config_t for forward compatibility

---

driver/cam_hal.c

Add missing error code validation in cam_hal.
Fixes #699

Fixes missing return error code validation during camera initialization

---

driver/include/esp_camera.h

Cleanup: remove instruction to call camera_probe from the documentation for esp_camera_init. camera_probe is not a public function. Actually, esp_camera_init calls camera_probe, so the documentation is backwards.
Comment-only change.

Remove instruction to call camera_probe

---

conversions/esp_jpg_decode.c
conversions/to_bmp.c

esp_jpg_decode does not return if writer fails, causing unhandled exceptions. Also logs when rgb_write malloc fails.
---

Add error handling for esp_jpg_decode

---

driver/cam_hal.c

x## Description
Changes:
* Store SOI as a 3-byte array (0xFF D8 FF) and use sizeof() everywhere.
* Early-exit when length < 3 to avoid over-reading
* calculate end index correctly, to avoid over-reading
In the search for the cause of crashes reported by @turenkomv here: https://github.com/esphome/esphome/pull/8832#issuecomment-2897275655 I found this overread of a pointer, which can cause undefined behaviour.

fix(cam_hal): prevent SOI scan from (1) running on length<3 and (2) over-reading the last 2 bytes

---

driver/cam_hal.c

If DMA returns a frame shorter than two bytes, the previous code did:
dptr = inbuf + length - 2;
which under-flows the pointer and produces undefined behaviour.
Behaviour for valid frames (length ≥ 2) is unchanged; damaged or empty buffers are now discarded safely.
In the search for the cause of crashes reported by @turenkomv here: https://github.com/esphome/esphome/pull/8832#issuecomment-2897275655 I found this underflow of a pointer, which can cause undefined behaviour.
@turenkomv would you be so kind and would test this on your hardware? Tag is `fixes_for_m5_0.2`, which is the currently used version in ESPHome with both patches on top.

fix(cam_hal): guard cam_verify_jpeg_eoi() against buffer-underflow

---

sensors/hm0360.c

This pull-request eliminates the corner-case in the HM0360 driver where a failed SCCB/I²C read could silently corrupt the sensor’s PLL configuration, and it tidies up related compiler noise.
* `read_reg()` returns a negative error on bus failure.
Previously `_set_pll()` copied that raw `int` into an 8-bit variable and wrote it back to **PLL1CFG**, so any error (e.g. `-1 → 0xFF`) overwrote the register while the function still reported 'success'.
* `read_reg()` return data is checked for the data width. If 16-bit data is supplied it's no longer truncated to 8 bit and instead an error is returned.
* Extra PLL parameters are currently unused and triggered `-Wunused-parameter` warnings.

hm0360: harden _set_pll() against read-failures & bad widths, silence unused-param warnings

---

driver/sccb-ng.c

SCCB_Install_Device() rejected new devices only when device_count > MAX_DEVICES. When device_count == MAX_DEVICES the function still proceeded to install the device and wrote to devices[device_count], i.e. devices[MAX_DEVICES], which is one element past the end of the devices[] array (valid indices 0..MAX_DEVICES-1).
This off-by-one results in a buffer overflow / write outside the designated memory area and then increments device_count to MAX_DEVICES+1.
Change the guard to `device_count >= MAX_DEVICES` so we refuse installation once the array is full and prevent the out-of-bounds write/read chain.

sccb-ng: fix off-by-one device capacity check to prevent overflow

---

driver/cam_hal.c

Previously there is no limit how much data would be transferred via DMA from the camera (in psram_mode).
Added a DMA overflow detection block in cam_task() so the driver stops if the number of frame copies exceeds the is reaching the maximum amount of storage allocated in PSRAM.

cam_hal: add guard in cam_task() so DMA transfers cannot exceed image slot size

---

Kconfig
README.md
driver/cam_hal.c
driver/esp_camera.c
driver/include/esp_camera.h
driver/private_include/cam_hal.h
test/test_camera.c

Add a Kconfig switch (CONFIG_CAMERA_PSRAM_DMA) to enable camera to PSRAM
DMA copy on ESP32-S2 and ESP32-S3 targets, in favor of removing the
undocumented "set XCLK=16MHz to enable PSRAM DMA" heuristic.
cam_hal.c:
- Select psram_mode = true when CONFIG_CAMERA_PSRAM_DMA && target is S2/S3.
- Otherwise psram_mode = false.
- Log whether PSRAM DMA mode is enabled.
Kconfig:
- New bool CAMERA_PSRAM_DMA (default n) under Camera configuration.
Runtime control:
- New public API:
- esp_camera_set_psram_mode(bool enable)
- esp_camera_get_psram_mode(void)
- esp_camera_reconfigure(const camera_config_t *cfg)
README/test:
- Remove stale 16MHz XCLK comments.
- Add short note describing CONFIG_CAMERA_PSRAM_DMA.

feat: add PSRAM-DMA flag + runtime API for ESP32-S2/S3; remove 16MHz heuristic

---

driver/cam_hal.c

**This patch required #776 and thus contains the commit of this PR.**
- Added a configurable probe length for PSRAM JPEG validation via CAM_EOI_PROBE_BYTES
- For PSRAM mode, CAM_EOI_PROBE_BYTES is copied from the first DMA block into a
stack buffer and validated by cam_verify_jpeg_eoi() to verify that it's a valid
jpeg image.
- Reading from PSRAM directly with cam_verify_jpeg_eoi() is here avoided due to
latency of small operations done by cam_verify_jpeg_eoi().
Related https://github.com/espressif/esp32-camera/issues/775, #776

fix jpeg eoi check for psram_mode (DMA)

---

driver/cam_hal.c

Replace Log message handler with a more lightweight version in an effort to reduce stack usage.
Stack usage by log output crashed the cam_task here:
https://github.com/espressif/arduino-esp32/issues/11672
And here:
https://github.com/espressif/arduino-esp32/issues/11674
---

replace Log message handler with a more lightweight version
